return {
	require("config.plugins.zenbones"),
	require("config.plugins.lualine"),
	require("config.plugins.treesitter"),
	require("config.plugins.conform"),
	require("config.plugins.telescope"),
	require("config.plugins.nightfox"),
	require("config.plugins.blinkcmp"),
	require("config.plugins.oil"),
	require("config.plugins.gitsigns"),
	require("config.plugins.rainbowdelimiters"),
	require("config.plugins.autotag"),
	require("config.plugins.autopairs"),
	require("config.plugins.tabout"),
	require("config.plugins.alpha"),
}
